# H4 charts -> tables they read; render_index() writes docs/figure_index.md
from .config import ROOT

# table -> (builder, run_pipeline step)
BUILDERS = {
    "processed Parquet (data/processed)": ("io_reddit.build_all", "clean"),
    "overview_counts": ("aggregates.overview_counts", "aggregates"),
    "lexicon_terms_by_month": ("textmining.term_counts (after build_matches)", "text"),
    "lexicon_terms_daily": ("textmining.term_counts (after build_matches)", "text"),
    "per-comment features (data/processed/derived)": ("textmining.build_features", "features"),
    "daily_features": ("events.build_daily", "events"),
    "event_effects": ("events.effects_table", "events"),
}

# id, fn (cell in eda.ipynb), section in eda.ipynb (4.x), tables, what it shows
FIGURES = [
    ("C20", "c20", "4.3", ["daily_features"], "Crisis words per 10,000 words, one line per subreddit"),
    ("C20b", "c20b", "4.4", ["daily_features", "event_effects"], "Event words after vs before, bars per event"),
    ("C21", "c21", "4.5", ["daily_features", "event_effects"], "Tone change tiles, 4 groups x 4 events"),
    ("C22", "c22", "4.6", ["daily_features"], "r/nosurf doomscroll mentions per 10,000 words, weekly, smoothed"),
    ("C23", "c23", "4.7", ["lexicon_terms_by_month", "overview_counts"], "Brainrot words per 10,000 in r/memes + r/teenagers, stream graph"),
    ("C24", "c24", "4.8", ["processed Parquet (data/processed)"], "r/nosurf session length buckets, before vs after"),
    ("C26", "c26", "4.9", ["per-comment features (data/processed/derived)"], "r/nosurf per-author tone change, raincloud"),
]


def render_index(path=None):
    rows = ["# Figure index: the H4 charts and the code behind them\n",
            "Generated by `src/figure_registry.py`. Each chart is drawn by a code cell in the H4 section of `eda.ipynb` (nothing is saved to disk); "
            "the tables it reads are built by the steps of `run_pipeline.py`.\n",
            "| Figure | Drawn by | Question | Reads | Tables built by | What it shows |", "|---|---|---|---|---|---|"]
    for cid, fn, q, inputs, shows in FIGURES:
        built = "; ".join(f"`{BUILDERS[t][0]}`" for t in inputs)
        rows.append(f"| {cid} | `eda.ipynb` cell `{fn}()` | {q} | {', '.join(f'`{t}`' for t in inputs)} | {built} | {shows} |")
    path = path or ROOT / "docs" / "figure_index.md"
    path.write_text("\n".join(rows) + "\n")
    return path
