"""One entry per H4 chart: the code cell of eda.ipynb that draws it, the tables it reads and the step that builds them.

`python -c "from src.figure_registry import render_index; render_index()"` (or `python run_pipeline.py index`) writes docs/figure_index.md.
"""
import ast

import nbformat

from .config import ROOT

# table -> (function that builds it, run_pipeline step)
BUILDERS = {
    "processed Parquet (data/processed)": ("io_reddit.build_all", "clean"),
    "overview_counts": ("aggregates.overview_counts", "aggregates"),
    "lexicon_terms_by_month": ("textmining.term_counts (after build_matches)", "text"),
    "lexicon_terms_daily": ("textmining.term_counts (after build_matches)", "text"),
    "per-comment features (data/processed/derived)": ("textmining.build_features", "features"),
    "daily_features": ("events.build_daily", "events"),
    "event_effects": ("events.effects_table", "events"),
}

# id, function (a code cell of the H4 section of eda.ipynb), question in that section, input tables
FIGURES = [
    ("C20", "c20", "H4 Q1", ["daily_features"]),
    ("C20b", "c20b", "H4 Q2", ["daily_features", "event_effects"]),
    ("C21", "c21", "H4 Q3", ["daily_features", "event_effects"]),
    ("C22", "c22", "H4 Q4", ["daily_features"]),
    ("C23", "c23", "H4 Q5", ["lexicon_terms_by_month", "overview_counts"]),
    ("C24", "c24", "H4 Q6", ["processed Parquet (data/processed)"]),
    ("C26", "c26", "H4 Q7", ["per-comment features (data/processed/derived)"]),
]


def _nb_doc(fn):
    """First docstring line of a chart function that lives in a code cell of eda.ipynb."""
    for c in nbformat.read(ROOT / "eda.ipynb", 4).cells:
        if c.cell_type == "code" and f"def {fn}(" in c.source:
            for n in ast.parse(c.source).body:
                if isinstance(n, ast.FunctionDef) and n.name == fn:
                    return (ast.get_docstring(n) or "").split("\n")[0]
    return ""


def render_index(path=None):
    rows = ["# Figure index: the H4 charts and the code behind them\n",
            "Generated by `src/figure_registry.py`. Each chart is drawn by a code cell in the H4 section of `eda.ipynb` (nothing is saved to disk); "
            "the tables it reads are built by the steps of `run_pipeline.py`.\n",
            "| Figure | Drawn by | Question | Reads | Tables built by | What it shows |", "|---|---|---|---|---|---|"]
    for cid, fn, q, inputs in FIGURES:
        built = "; ".join(f"`{BUILDERS[t][0]}`" for t in inputs)
        rows.append(f"| {cid} | `eda.ipynb` cell `{fn}()` | {q} | {', '.join(f'`{t}`' for t in inputs)} | {built} | {_nb_doc(fn)} |")
    path = path or ROOT / "docs" / "figure_index.md"
    path.write_text("\n".join(rows) + "\n")
    return path
